from methods_registry import MethodName
from model_problem_visual import run_model_problem_plots
from three_body_visual import run_three_body_plots, animate_three_body


run_model_problem_plots()
run_three_body_plots()
animate_three_body(method_name=MethodName.VELOCITY_VERLET)

